
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jomer
 */
public class EditProfile extends javax.swing.JFrame {

    // Declare a variable holding the account number requesting for editing information
    String accountNumber;
   
    
    public EditProfile(String number) {
        initComponents();
        
        // Initialize the variable holding the account number
        accountNumber = number;

        // displays the account details
        displayAccountDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fullname = new javax.swing.JTextField();
        month = new javax.swing.JSpinner();
        day = new javax.swing.JSpinner();
        year = new javax.swing.JSpinner();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullnameActionPerformed(evt);
            }
        });
        getContentPane().add(Fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 350, 30));
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 80, 20));
        getContentPane().add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 80, -1));
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 80, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 350, 30));
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 350, 30));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 350, 30));

        updateBtn.setBorderPainted(false);
        updateBtn.setContentAreaFilled(false);
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateBtnMousePressed(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditProfile.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 576));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    public void displayAccountDetails() {
        
        // fetch the initial data
        String initialName = "";
        Integer initialMonth = 0;
        Integer initialDay = 0;
        Integer initialYear = 0;
        String initialEmail = "";
        String initialPhone = "";
        String initialAddress = "";
        
        try {
            BufferedReader reader = new BufferedReader(new FileReader("accounts.csv"));
            String line;
            
            while ((line = reader.readLine())!=null) {
                String[] accountDetails = line.split(",");
                
                if (accountDetails[0].equals(accountNumber)) {
                    Fullname.setText(accountDetails[1]);
                    month.setValue(Integer.valueOf(accountDetails[5].split("/")[0]));
                    day.setValue(Integer.valueOf(accountDetails[5].split("/")[1]));
                    year.setValue(Integer.valueOf(accountDetails[5].split("/")[2]));
                    email.setText(accountDetails[2]);
                    phone.setText(accountDetails[3]);
                    address.setText(accountDetails[4]);
                }
            }
        } 
        catch (FileNotFoundException ex) {
        Logger.getLogger(EditProfile.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EditProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void FullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullnameActionPerformed

    }//GEN-LAST:event_FullnameActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed

    private void updateBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMousePressed
        // fetch the input
        String newName = Fullname.getText();
        String newMonth = String.valueOf(month.getValue());
        String newDay = String.valueOf(day.getValue());
        String newYear = String.valueOf(year.getValue());
        String newEmail = email.getText();
        String newPhone = phone.getText();  
        String newAddress = address.getText();
        
        // transfer the file to a temporary file
        try {
            BufferedReader reader = new BufferedReader(new FileReader("accounts.csv"));
            PrintWriter writer = new PrintWriter(new FileWriter("TemporaryFile.csv"));
            String line;
            
            while ((line = reader.readLine())!=null) {
                String[] accountDetails = line.split(",");
                
                writer.append(String.format("%s,%s,%s,%s,%s,%s,%s\n",
                        accountDetails[0],
                        accountDetails[1],
                        accountDetails[2],
                        accountDetails[3],
                        accountDetails[4],
                        accountDetails[5],
                        accountDetails[6]));
            }
            
            reader.close();
            writer.close();
        } 
        catch (FileNotFoundException ex) {
        Logger.getLogger(EditProfile.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EditProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // transfer the temporary file to original file 
        try {
            BufferedReader reader = new BufferedReader(new FileReader("TemporaryFile.csv"));
            PrintWriter writer = new PrintWriter(new FileWriter("accounts.csv"));
            String line;
            
            while ((line = reader.readLine())!=null) {
                String[] accountDetails = line.split(",");
                
                // Search for the account
                if (!accountDetails[0].equals(accountNumber)) {
                    writer.append(String.format("%s,%s,%s,%s,%s,%s,%s\n",
                            accountDetails[0],
                            accountDetails[1],
                            accountDetails[2],
                            accountDetails[3],
                            accountDetails[4],
                            accountDetails[5],
                            accountDetails[6]));
                }
                else {
                    // edit the specific account
                    writer.append(String.format("%s,%s,%s,%s,%s,%s,%s\n",
                            accountDetails[0],
                            newName,
                            newEmail,
                            newPhone,
                            newAddress,
                            String.format("%s/%s/%s", newMonth, newDay, newYear),
                            accountDetails[6]));
                }
            }
            
            reader.close();
            writer.close();
        } 
        catch (FileNotFoundException ex) {
        Logger.getLogger(EditProfile.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EditProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_updateBtnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfile(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fullname;
    private javax.swing.JTextField address;
    private javax.swing.JSpinner day;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner month;
    private javax.swing.JTextField phone;
    private javax.swing.JButton updateBtn;
    private javax.swing.JSpinner year;
    // End of variables declaration//GEN-END:variables
}
